### PR TITLE
utcaApp: build with PVXS qsrv.

### PR DESCRIPTION
**Pull request by ericonr**

### CODE REVIEW

**Comment by ericonr** [comment]
@gustavosr8

**Comment by gustavosr8** [comment]
@ericonr, what is the result of `pvinfo $(P)$(R)TableLabels` and `pvget $(P)$(R)TableLabels`?

**Comment by ericonr** [comment]
> @ericonr, what is the result of `pvinfo $(P)$(R)TableLabels` and `pvget $(P)$(R)TableLabels`?

```
~/p/g/afc-timing-gw dbg-upstream ➜ pvget DE-23SL17:DI-BPM:TableLabels
DE-23SL17:DI-BPM:TableLabels <undefined>              INVALID DRIVER UDF ["Amplitude A", "Amplitude B", "Amplitude C", "Amplitude D", Q, Sum, "Position X", "Position Y"]
~/p/g/afc-timing-gw dbg-upstream ➜ pvinfo DE-23SL17:DI-BPM:TableLabels
DE-23SL17:DI-BPM:TableLabels
Server: 10.20.26.23:39273
Type:
    epics:nt/NTScalarArray:1.0
        string[] value
        alarm_t alarm
            int severity
            int status
            string message
        time_t timeStamp
            long secondsPastEpoch
            int nanoseconds
            int userTag
        structure display
            string description
            string units
```

**Comment by gustavosr8** [comment]
@ericonr wrong PV, sorry. I mean `$(P)$(R)Monit-Mon`

**Comment by ericonr** [comment]
```
~/p/g/afc-timing-gw dbg-upstream ➜ pvinfo DE-23SL17:DI-BPM:{GENData,Monit}-Mon
DE-23SL17:DI-BPM:GENData-Mon
Server: 10.20.26.23:37581
Type:
    epics:nt/NTTable:1.0
        structure record
            structure _options
                int queueSize
                boolean atomic
        alarm_t alarm
            int severity
            int status
            string message
        time_t timeStamp
            long secondsPastEpoch
            int nanoseconds
            int userTag
        string descriptor
        string[] labels
        structure value
            int[] A
            int[] B
            int[] C
            int[] D
            double[] Q
            double[] S
            double[] X
            double[] Y

DE-23SL17:DI-BPM:Monit-Mon
Server: 10.20.26.23:37581
Type:
    structure
        structure record
            structure _options
                int queueSize
                boolean atomic
        alarm_t alarm
            int severity
            int status
            string message
        time_t timeStamp
            long secondsPastEpoch
            int nanoseconds
            int userTag
        string[] labels
        structure value
            int A
            int B
            int C
            int D
            double Q
            double S
            double X
            double Y

~/p/g/afc-timing-gw dbg-upstream ➜ pvget DE-23SL17:DI-BPM:{GENData,Monit}-Mon
DE-23SL17:DI-BPM:GENData-Mon 2024-11-22 11:37:53.580
"Amplitude A" "Amplitude B" "Amplitude C" "Amplitude D"            Q   Sum "Position X" "Position Y"
           45            48            56            39       586757  65.8      -849437     -21850.5
           50            41            46            45       439560  63.7       352713     -19379.8
           47            50            41            33       308721 59.85      -546550    1.092e+06
           47            50            29            40      -761392  58.1       502924  1.39181e+06
           40            37            29            41      -529870 51.45       842809       432553
           35            45            33            50 -1.31928e+06 57.05       328173     -92879.3
           39            52            30            41 -1.19115e+06  56.7      48620.9       994857
           43            29            34            49      54886.2 54.25  1.49317e+06      -558109
           46            33            38            36       766336 53.55       554865       207039
           28            36            44            33      71428.6 49.35  -1.0628e+06      -714976
           44            36            32            26       813793  48.3     -13582.3  1.27674e+06
           49            47            33            37      -145238  58.1       304297  1.25668e+06
           50            45            34            39     -63446.3  58.8       476190  1.04762e+06
           41            28            38            30  1.22421e+06 47.95       289830      13967.7
           38            48            45            38      -127767 59.15      -802466       127767
DE-23SL17:DI-BPM:Monit-Mon   structure
    structure record
        structure _options
            boolean atomic true
    alarm_t alarm
        int severity 0
        int status 0
        string message
    time_t timeStamp 2024-11-22 11:40:35.458
        long secondsPastEpoch 1732286435
        int nanoseconds 458159289
        int userTag 0
    string[] labels ["Amplitude A", "Amplitude B", "Amplitude C", "Amplitude D", Q, Sum, "Position X", "Position Y"]
    structure value
        int A 22
        int B 22
        int C 22
        int D 22
        double Q 0
        double S 30.8
        double X 0
        double Y 0
```

**Comment by ericonr** [comment]
Merging this might wait for https://github.com/epics-base/pvxs/pull/91

**Comment by ericonr** [comment]
We are going to use in-db group definitions for now.

When a release is made with the linked fix and we can switch to it, we can move everything into json files.

**Pull request merged**
